version: "3"

services:
  keycloud-db:
    image: postgres
    restart: always
    command: -p $POSTGRES_PORT
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_DB=$POSTGRES_DB
    ports:
      - $POSTGRES_PORT:$POSTGRES_PORT
    expose:
      - $POSTGRES_PORT

  keycloud-backend:
    image: zkdev/keycloud-app:latest
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PORT=$POSTGRES_PORT
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_HOST=$POSTGRES_HOST
    depends_on:
      - keycloud-db
    restart: always
    ports:
      - 8080:8080
    expose:
      - 8080

  nginx:
    image: nginx:latest
    container_name: production_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/error.log:/etc/nginx/error_log.log
      - ./nginx/cache/:/etc/nginx/cache
      - /etc/letsencrypt/:/etc/letsencrypt/
    ports:
      - 80:80
      - 443:443
