version: "3"

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_DB=$POSTGRES_DB
    ports:
      - 5432:5432

  app:
    image: zkdev/keycloud-app:v0.0.1
    depends_on:
      - db
    restart: always
    ports:
      - 8080:8080
